name: birrawrapped
description: "La millor aplicaciÃ³ per a saber les birres que arribes a beure!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  intl: ^0.20.2
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

  fonts:
    - family: Kameron
      fonts:
        - asset: assets/fonts/Kameron-Regular.ttf
        - asset: assets/fonts/Kameron-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kameron-Medium.ttf
          weight: 500
        - asset: assets/fonts/Kameron-SemiBold.ttf
          weight: 600
